### ISSUE TITLE
Show latest commit contents optionally

### ISSUE THREAD

**Issue by vednoc** [StylishThemes/Feature-Override-Styles#6]
**Describe the change you'd like**

I'd like to be able to see the latest commit without having to click on the toggle button.

**Additional context**

This action can be reversed to _hide_ the latest commit (not sure _why_ anyone would want that) when toggled.

I already made the userstyle for it, just not sure how to name it or where to put it. It doesn't need GHD to function, so I ended up dropping `dark` from the name on my local userstyle.

Here's how it looks:

![peek-show-latest-commit](https://user-images.githubusercontent.com/18245694/85771709-78b02b00-b71c-11ea-9231-897790bd8cf7.gif)

One of the downsides could be _very long_ commit messages. This can be worked around by adding `max-height` to the message details, preferably customizable, since GitHub seems to be able to show the _entire_ message without truncating it.

![image](https://user-images.githubusercontent.com/18245694/85772306-fecc7180-b71c-11ea-9cae-97627b678763.png)

**Comment by the-j0k3r** [comment]
By default show nothing, That would be the way to go, the  on toggle show whatever. FYI I prefer not by default.

**Comment by vednoc** [comment]
Sure thing!

Where should I put the code, or what should I call the new file?

I would prefer to see the actual commit summary, not the entire commit message. The current default that shows commit hash and when it was committed is frankly useless.

**Comment by the-j0k3r** [comment]
Perhaps a new file, where one could aggregate a collection of similar user hacks. Name idk,something with `github-ui-hacks.user.css` or similar.

One issue I came across was with things like this https://github.com/StylishThemes/Feature-Override-Styles/blob/master/github-dark-element-borders.user.css, I had to add the else, because without whne the toggle for the option was off, the style no longer showed up as active for that site in stylus popup.

I think we may need a similar hack on this so that the style always shows on popup no matter state of toggle.

You probably know a better way around the issue =)

**Comment by vednoc** [comment]
> Name idk,something with `github-ui-hacks.user.css` or similar.

Seems good to me. Also, wouldn't it be better if the style had `.styl` instead of `.css` extension? Seems more fitting since we're using Stylus-lang preprocessor.


> when the toggle for the option was off, the style no longer showed up as active for that site

Yeah, ran into that issue as well. Perhaps some dummy rule can be added just so it shows in the popup, otherwise we can stick to using GitHub's default rules. I'll try a few different things to work around it. 😃

**Comment by the-j0k3r** [comment]
> Also, wouldn't it be better if the style had `.styl` instead of `.css` extension? Seems more fitting since we're using Stylus-lang preprocessor.

I dont mind personally. =)



> Yeah, ran into that issue as well. Perhaps some dummy rule can be added just so it shows in the popup, otherwise we can stick to using GitHub's default rules. I'll try a few different things to work around it. smiley

I think a dummy rule maybe OK, But do by all means try other things, Im sure whatever you come up with, will work:tm:

**Comment by the-j0k3r** [comment]
Feel free to create this style ASAYC I have other hacks that could fit into this nicely like 

```css
@var checkbox addreadBoxHeaderBgw  "Add readme box header background" 1


	if readme-box-header-bgw {
		#readme .Box-header.bg-white {
			background-color: headerBackground !important;
			border-bottom: 1px solid #343434 !important;
			padding: 10px 16px !important;
		}
	}
```

**Comment by the-j0k3r** [comment]
I think at some stage  we need to think about merging some of these styles into a single SEPARATE style (Without removing the originals), its stupid to have 10 styles for one site, just because GHD is having a alpha moment or other reasons..

TBH Ide rather use this opportunity, so a fitting name to merge these things into, even if its just for a couple of ppl to use.

Problem is, when it comes to updating one style thats exists as standalone and part of another, both need updating. Im unsure of a better way to do this, short of maintaining a separate fork for GitHub Dark with all of these built in.

rant:

The org owner @silverwind  will not go the way of `@preprocessor stylus`,[ I dont fully understand the logic because seems to think we need to use SCSS or LESS and we dont.](https://github.com/StylishThemes/GitHub-Dark/issues/1007), the options alone would be cleaner, we wouldn't need to pull hairs out., so, using ifs and elses is out, and doing this without, like GHD dark does currently is not efficient or possible with all options and to try is a silly silly nightmare.

The death of opensource in nigh lol, forking because of fundamental differences is a huge issue, as is this org has 3 active devs, external contributors are few and far far far in-between, A new fork would be 1 dev only.

**Comment by vednoc** [comment]
Just realized my PR wasn't actually submitted for some reason. xd I'll do it tomorrow and reply to your idea about merging userstyles with similar goals. I have to go for now.

**Comment by the-j0k3r** [comment]
looking forward to it

**Comment by vednoc** [comment]
> merging some of these styles into a single SEPARATE style (Without removing the originals)

I vote for removing them after _some_ amount of time. Stylus' defaults to updating every 24 hours, although some users keep it disabled (I do, too), but with that we could update `@updateURL` fields and the migration will be "forced". We could also add some sort of alert that styles will be merged and deleted (in a week/month/etc), or perhaps not deleted but just obsolete/deprecated. LMK what you think about that.

> short of maintaining a separate fork for GitHub Dark with all of these built in.

I don't wanna touch GHD -- that thing scares me! 😄 

> `@preprocessor stylus`

The options would indeed be much cleaner, but there is also backwards-compatibility factor I think. Ultimately you could have both `stylus` and `USo` preprocessors in separate versions of GHD, one customizable and the other _not_ customizable. Pretty much how I do my userstyles. One issue with customizable version of GHD is that it could take a _while_ to compile to CSS due to how large GHD is whenever an option is changed.

**Comment by darkred** [comment]
> I already made the userstyle for it, just not sure how to name it or where to put it. It doesn't need GHD to function, so I ended up dropping dark from the name on my local userstyle.

@vednoc, I'd like to make a suggestion, in case you use the popular browser extension, "Refined GitHub", like me, and the following issue has missed your attention:

This issue https://github.com/sindresorhus/refined-github/issues/3277 aims at the same thing as this issue, and it's been recently tagged as `Help wanted`.
Maybe you'd like to contribute your CSS as a new Refined GitHub feature, instead of making a separate userstyle file here?

I hope you find my suggestion constructive/useful 🙂

**Comment by vednoc** [comment]
@darkred I used to use Refined GitHub, so I'll have to install it again to see what it takes to implement this feature over there. For now, you could try out the solution I came up with.

Thanks for letting me know about it! 😊

**Comment by darkred** [comment]
Glad to be of help! And, your userstyle works fine, thank you.

**Comment by the-j0k3r** [comment]
> Maybe you'd like to contribute your CSS as a new Refined GitHub feature, instead of making a separate userstyle file here?

Maybe not everyone uses Refined GitHub like you (I dont). So this PR is fine. =)

**Comment by darkred** [comment]
The latest feature preview, "Latest commit design updates" :
>  keeps the first line of the commit message visible on desktop screen sizes

<details>
<summary>Screenshot</summary>

![2020-07-08_120902](https://user-images.githubusercontent.com/723651/86900382-f2c8b280-c113-11ea-86f4-9576842f34cf.jpg)
</details>

**Comment by the-j0k3r** [comment]
> The latest feature preview, "Latest commit design updates" :

I dont think the PR it is affected by it.

**Comment by silverwind** [comment]
Feel free to use whatever preprocessor you like in these addon styles, I don't really contribute here much if at all so I couldn't care less.

**Comment by the-j0k3r** [comment]
@silverwind those comments about preprocessor were regarding GitHub Dark not these addon styles.

**Comment by silverwind** [comment]
I'm not totally opposed to a different preprocessor but as I'm a CSS purist, stylus just looks so alien to me. Can it be done in LESS? I imagine we need to drop a few techniques (color interpolation in svg backgrounds for example) used in GHD but I'm all for removing some of that complexity.

**Comment by the-j0k3r** [comment]
We dont have to do anything differently, Pure CSS is fully supported. and especially we dont need to use LESS, or drop anything you mentioned, except for the how the options are done That alone It would be much cleaner and would allow more control.

just not having to use uso variables `/*[[whatever]]*/` and just use `whatever` and EOT etc and so on is a blessing that opens doors to manipulate the css in ways that dont affect how we work or support inspector side.

If I get some help on the syntax themes automation of some todo list items, I can work on a POC for that.
